language: crystal

before_install:
  - sudo apt-get install beanstalkd

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: beanstalk-cr
  on:
    branch: master
  local_dir: docs

script:
  - crystal spec
  - crystal docs
#   - crystal tool format --check
